"""Professional MoM Word document with every required output section."""
from docx import Document
from docx.shared import Pt

from .ai_understanding import DEFAULT_DEADLINE, DEFAULT_OWNER


def _paragraphs(doc, text, empty="Not available."):
    blocks = [b.strip() for b in (text or "").split("\n\n") if b.strip()]
    for b in blocks or [empty]:
        doc.add_paragraph(b)


def _bullets(doc, items, empty="None recorded."):
    for x in items or [empty]:
        doc.add_paragraph(str(x), style="List Bullet" if items else "Normal")


def _table(doc, headers, rows, empty):
    if not rows:
        doc.add_paragraph(empty)
        return
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"
    for cell, head in zip(table.rows[0].cells, headers):
        cell.text = head
        for run in cell.paragraphs[0].runs:
            run.bold = True
    for row in rows:
        cells = table.add_row().cells
        for cell, value in zip(cells, row):
            cell.text = str(value or "")
    for row in table.rows:
        for cell in row.cells:
            for p in cell.paragraphs:
                for run in p.runs:
                    run.font.size = Pt(9)


def build_mom_doc(metadata, ai):
    doc = Document()
    doc.add_heading("Minutes of Meeting", level=0)
    doc.add_paragraph(metadata.get("title") or "Meeting")

    table = doc.add_table(rows=0, cols=2)
    table.style = "Table Grid"
    for key, label in (("date", "Meeting Date"), ("start_time", "Start Time"), ("end_time", "End Time"),
                       ("venue", "Venue"), ("mode", "Mode"), ("agenda", "Agenda")):
        if metadata.get(key):
            row = table.add_row().cells
            row[0].text, row[1].text = label, str(metadata[key])
    participants = metadata.get("participants") or []
    if participants:
        row = table.add_row().cells
        row[0].text = "Participants"
        row[1].text = "; ".join(
            f"{p.get('name', '')}" + (f" ({p['designation']})" if p.get("designation") else "")
            if isinstance(p, dict) else str(p) for p in participants)

    doc.add_heading("Executive Summary", level=1)
    _paragraphs(doc, ai.get("executive_summary"))
    doc.add_heading("Complete Conversation Summary", level=1)
    _paragraphs(doc, ai.get("complete_conversation_summary"))
    doc.add_heading("Key Discussion Points", level=1)
    _bullets(doc, ai.get("discussion_points"))

    doc.add_heading("Decisions", level=1)
    _table(doc, ["Decision", "Timestamp", "Evidence", "Review flag"],
           [(d["decision"], d["timestamp"], d["evidence"], d["review_flag"]) for d in ai.get("decisions", [])],
           "No decisions were explicitly recorded.")

    doc.add_heading("Action Items", level=1)
    _table(doc, ["Action", "Owner", "Deadline", "Timestamp", "Evidence", "Review flag"],
           [(a["action"], a.get("owner", DEFAULT_OWNER), a.get("deadline", DEFAULT_DEADLINE),
             a["timestamp"], a["evidence"], a["review_flag"]) for a in ai.get("action_items", [])],
           "No action items were explicitly recorded.")

    doc.add_heading("Commitments", level=1)
    _table(doc, ["Commitment", "Owner", "Deadline", "Timestamp", "Evidence", "Review flag"],
           [(c["commitment"], c.get("owner", DEFAULT_OWNER), c.get("deadline", DEFAULT_DEADLINE),
             c["timestamp"], c["evidence"], c["review_flag"]) for c in ai.get("commitments", [])],
           "No commitments were explicitly recorded.")

    doc.add_heading("Open Questions / Pending Follow-up", level=1)
    _bullets(doc, ai.get("open_questions"))
    doc.add_heading("Next Meeting", level=1)
    _bullets(doc, ai.get("next_meeting"), empty="Not explicitly stated.")
    doc.add_heading("Review Flags", level=1)
    _bullets(doc, ai.get("review_flags"), empty="No review flags.")

    note = doc.add_paragraph()
    run = note.add_run("This document was generated by AI from the meeting recording. Owners, deadlines and "
                       "decisions appear only where explicitly stated. Review flagged items against the recording.")
    run.italic = True
    run.font.size = Pt(8)
    return doc
